routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
// use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::view('/admin/login','admin.auth.login');
Auth::routes();
Route::get('/logout', 'Admin\HomeController@logout')->name('logout');
Route::group(['prefix' => '/admin', 'middleware'=>['auth']],function(){

    // Dashboard
    Route::get('/dashboard', 'Admin\HomeController@index')->name('dashboard');
    // contact
    Route::resource('/contact','Admin\ContactController');
    //profile
    Route::get('/profile', 'Admin\AdminProfileController@profile')->name('admin-profile');
    Route::post('/profile/update/{id}', 'Admin\AdminProfileController@update')->name('admin-profile-update');
    Route::post('/profile/changepassword/{id}','Admin\AdminProfileController@changePassword');
});
Route::get('/', 'frontend\HomeController@index');
Route::post('/contactus', 'frontend\HomeController@insert');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $table = 'contacts';
}

app/Http/Controllers/Admin/ContactController.php
<?php




namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;

use App\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{

    public function index()
    {
        $contacts = Contact::get();
        return view('admin.contact.index',compact('contacts'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(Contact $contact)
    {
        //
    }

    public function edit(Contact $contact)
    {
        //
    }

    public function update(Request $request, Contact $contact)
    {
        //
    }

    public function destroy($id)
    {
        Contact::find($id)->delete();
        return back()->with('success','Contact Deleted Successfully!');
    }
}

resources/views/admin/contact/index.blade.php
@extends('admin.layout.master')
@section('container')
<div class="row">
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header">
                <div class="row">
                    <div class="col-8">
                        <h4>Contact</h4>
                    </div>
                    <div class="col-4 text-right">
                        @include('admin.layout.button')
                        {{-- <a href="#" class="btn btn-sm btn-primary">{{ __('Add user') }}</a> --}}
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover" id="ExportdataTable">
                        <thead class=" text-primary">
                            <th>#</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Contact</th>
                            <th>Subject</th>
                            <th>Message</th>
                            <th>Created Date</th>
                            <th></th>
                        </thead>
                        <tbody>
                            <?php $j=1 ?>
                            @foreach ($contacts as $contact)
                                <tr>
                                    <td>{{ $j++ }}</td>
                                    <td>{{ $contact->name }}</td>
                                    <td><a href="mailto:{{ $contact->email }}">{{ $contact->email }}</a></td>
                                    <td>{{ $contact->contact }}</td>
                                    <td>{{ $contact->subject }}</td>
                                    <td>{{ $contact->message }}</td>
                                    <td>{{ $contact->created_at->format('d/m/Y H:i') }}</td>
                                    <td>
                                        <form action="{{route('contact.destroy',$contact->id)}}" method="post">
                                            @csrf
                                            @method('delete')
                                            <button type="button" class="btn btn-link" data-toggle="tooltip" data-placement="bottom" title="Delete Contact" onclick="confirm('Are you sure you want to delete this sale? All your records will be permanently deleted.') ? this.parentElement.submit() : ''">
                                                <i class="tim-icons icon-simple-remove"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection