routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
// use SebastianBergmann\CodeCoverage\Report\Html\Dashboard;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::view('/admin/login','admin.auth.login');
Auth::routes();
Route::get('/logout', 'Admin\HomeController@logout')->name('logout');
Route::group(['prefix' => '/admin', 'middleware'=>['auth']],function(){

    // Dashboard
    Route::get('/dashboard', 'Admin\HomeController@index')->name('dashboard');
    // contact
    Route::resource('/contact','Admin\ContactController');
    //profile
    Route::get('/profile', 'Admin\AdminProfileController@profile')->name('admin-profile');
    Route::post('/profile/update/{id}', 'Admin\AdminProfileController@update')->name('admin-profile-update');
    Route::post('/profile/changepassword/{id}','Admin\AdminProfileController@changePassword');
});
Route::get('/', 'frontend\HomeController@index');
Route::post('/contactus', 'frontend\HomeController@insert');

resources/views/admin/layout/button.blade.php
<div class="btn-group export-btns">
    <button type="button" class="btn btn-sm btn-primary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-download"></i> Export </button>
    <div class="dropdown-menu">
            <a class="dropdown-item text-dark" id="export_print">
                <span class="navi-icon">
                    <i class="fa fa-print"></i>
                </span>
                <span class="navi-text ml-2">{{__('Print')}}</span>
            </a>

            <a class="dropdown-item text-success" id="export_excel">
                <span class="navi-icon">
                    <i class="fa fa-file-excel-o"></i>
                </span>
                <span class="navi-text ml-2">{{__('Excel')}}</span>
            </a>

            <a class="dropdown-item text-danger" id="export_pdf">
                <span class="navi-icon">
                    <i class="fa fa-file-pdf-o"></i>
                </span>
                <span class="navi-text ml-2">{{__('PDF')}}</span>
            </a>
    </div>
</div>

<style>
    .dt-buttons{
        display: none;
    }
</style>

resources/views/admin/layout/head.blade.php
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Docter</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@100;200;300;400;500;600&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.23.0/slimselect.min.css" rel="stylesheet">

    <!-- Icons -->
    <link href="{{ asset('assets/css/nucleo-icons.css')}}" rel="stylesheet" />
    <link rel="stylesheet" href="{{asset('assets/css/izitoast/css/iziToast.min.css')}}">
    <link  rel="stylesheet" href="{{ asset('assets/css/datatable/datatables.min.css')}}" type="text/css"/>
    <!-- CSS -->
    <link href="{{ asset('assets/css/white-dashboard.css?v=1.0.0')}}" rel="stylesheet" />
    <link href="{{ asset('assets/css/theme.css')}}" rel="stylesheet" />
</head>

resources/views/admin/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">
    @include('admin.layout.head')

    @include('admin.layout.sidebar')
    @include('admin.layout.nav')

    <body class="white-content">
        {{-- @auth() --}}
            <div class="wrapper">
                <div class="main-panel">

                    <div class="content">
                        @section('container')

                        @show
                    </div>

                </div>
            </div>
            {{-- <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form> --}}
        {{-- @else
            @include('layouts.navbars.navbar')
            <div class="wrapper wrapper-full-page">
                <div class="full-page {{ $contentClass ?? '' }}">
                    <div class="content">
                        <div class="container">
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        @endauth --}}

    @include('admin.layout.script')

    </body>
</html>

resources/views/admin/layout/nav.blade.php
<nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
                <button type="button" class="navbar-toggler">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <a class="navbar-brand" href="{{ route('dashboard') }}">Docter</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>
        <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ml-auto">

                <li class="dropdown nav-item">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <div class="photo">
                            @if(auth()->user()->image)
                            <img  src="{{ auth()->user()->image }}" alt="{{ __('Profile Photo') }}">
                            @else
                            <img  src="{{ asset('assets/img/default-avatar.png') }}" alt="{{ __('Profile Photo') }}">
                            @endif
                            {{-- <img src="{{ asset('assets/img/emilyz.jpg') }}" alt="{{ __('Profile Photo') }}"> --}}
                        </div>
                        {{-- <b class="caret d-none d-lg-block d-xl-block"></b>
                        <p class="d-lg-none">{{ __('Log out') }}</p> --}}
                    </a>
                    <ul class="dropdown-menu dropdown-navbar">
                        <li class="nav-link">
                            <a href="{{route('admin-profile')}}" class="nav-item dropdown-item">Profile</a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li class="nav-link">
                            <a href="/logout" class="nav-item dropdown-item" >Logout</a>
                        </li>
                    </ul>
                </li>
                <li class="separator d-lg-none"></li>
            </ul>
        </div>
    </div>
</nav>

resources/views/admin/layout/script.blade.php
        <script src="{{ asset('assets/js/core/jquery.min.js')}}"></script>
        <script src="{{ asset('assets/js/core/popper.min.js')}}"></script>
        <script src="{{ asset('assets/js/core/bootstrap.min.js')}}"></script>
        <script src="{{ asset('assets/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
        <!-- Chart JS -->
        {{-- <script src="{{ asset('assets/js/plugins/chartjs.min.js"></script> --}}
        <!--  Notifications Plugin    -->
        <script type="text/javascript" src="{{asset('assets/js/datatable/datatables.min.js')}}"></script>
        <script type="text/javascript" src="{{asset('assets/js/datatable/pdfmake.min.js')}}"></script>
        <script type="text/javascript" src="{{asset('assets/js/datatable/vfs_fonts.js')}}"></script>

        <script src="{{ asset('assets/js/plugins/bootstrap-notify.js')}}"></script>
        <script src="{{ asset('assets/js/plugins/chartjs.min.js') }}"></script>
        <script src="{{ asset('assets/js/white-dashboard.min.js?v=1.0.0')}}"></script>
        <script src="{{ asset('assets/js/theme.js')}}"></script>
        <script src="{{asset('assets/css/izitoast/js/iziToast.min.js')}}"></script>
            <script>
                @if(Session::has('success'))
                    iziToast.success({
                    title: '{{ session('success') }}',
                    position: 'topRight'
                });
                @endif
                @if(Session::has('error'))
                    iziToast.error({
                    title: '{{ session('error') }}',
                    position: 'topRight'
                });
                @endif
            </script>
        <script>
            $(document).ready(function() {
                $().ready(function() {
                    $sidebar = $('.sidebar');
                    $navbar = $('.navbar');
                    $main_panel = $('.main-panel');

                    $full_page = $('.full-page');

                    $sidebar_responsive = $('body > .navbar-collapse');
                    sidebar_mini_active = true;
                    white_color = false;

                    window_width = $(window).width();

                    fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

                    $('.fixed-plugin a').click(function(event) {
                        if ($(this).hasClass('switch-trigger')) {
                            if (event.stopPropagation) {
                                event.stopPropagation();
                            } else if (window.event) {
                                window.event.cancelBubble = true;
                            }
                        }
                    });

                    $('.fixed-plugin .background-color span').click(function() {
                        $(this).siblings().removeClass('active');
                        $(this).addClass('active');

                        var new_color = $(this).data('color');

                        if ($sidebar.length != 0) {
                            $sidebar.attr('data', new_color);
                        }

                        if ($main_panel.length != 0) {
                            $main_panel.attr('data', new_color);
                        }

                        if ($full_page.length != 0) {
                            $full_page.attr('filter-color', new_color);
                        }

                        if ($sidebar_responsive.length != 0) {
                            $sidebar_responsive.attr('data', new_color);
                        }
                    });

                    $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function() {
                        var $btn = $(this);

                        if (sidebar_mini_active == true) {
                            $('body').removeClass('sidebar-mini');
                            sidebar_mini_active = false;
                            whiteDashboard.showSidebarMessage('Sidebar mini deactivated...');
                        } else {
                            $('body').addClass('sidebar-mini');
                            sidebar_mini_active = true;
                            whiteDashboard.showSidebarMessage('Sidebar mini activated...');
                        }

                        // we simulate the window Resize so the charts will get updated in realtime.
                        var simulateWindowResize = setInterval(function() {
                            window.dispatchEvent(new Event('resize'));
                        }, 180);

                        // we stop the simulation of Window Resize after the animations are completed
                        setTimeout(function() {
                            clearInterval(simulateWindowResize);
                        }, 1000);
                    });

                    $('.switch-change-color input').on("switchChange.bootstrapSwitch", function() {
                            var $btn = $(this);

                            if (white_color == true) {
                                $('body').addClass('change-background');
                                setTimeout(function() {
                                    $('body').removeClass('change-background');
                                    $('body').removeClass('white-content');
                                }, 900);
                                white_color = false;
                            } else {
                                $('body').addClass('change-background');
                                setTimeout(function() {
                                    $('body').removeClass('change-background');
                                    $('body').addClass('white-content');
                                }, 900);

                                white_color = true;
                            }
                    });

                    $('.light-badge').click(function() {
                        $('body').addClass('white-content');
                    });

                    $('.dark-badge').click(function() {
                        $('body').removeClass('white-content');
                    });
                });
            });
            $(function () {
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
        <script>
            // datatable
            //start data export table
            var contacttable = $('#ExportdataTable').DataTable({
                language: {
                    paginate: {
                    next: '>', // '&#8594;' or '→'
                    previous: '<', //'&#8592;' or '←'
                    }
                },
                buttons: [
                    'print',
                    'copyHtml5',
                    'excelHtml5',
                    'csvHtml5',
                    'pdfHtml5',
                ],
            });


            $('#export_print').on('click', function(e) {
                e.preventDefault();
                contacttable.button(0).trigger();

            });


            $('#export_excel').on('click', function(e) {
                e.preventDefault();
                contacttable.button(2).trigger();

            });

            $('#export_pdf').on('click', function(e) {
                e.preventDefault();
                contacttable.button(4).trigger();

            });
            //end data export table
        // End datatable
        </script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.23.0/slimselect.min.js"></script>

resources/views/admin/layout/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="{{ request()->is('admin/dashboard') ? 'active' : '' }}">
                <a href="{{ route('dashboard') }}">
                    <i class="tim-icons icon-chart-bar-32"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            {{-- <li>
                <a data-toggle="collapse" href="#transactions">
                    <i class="tim-icons icon-bank" ></i>
                    <span class="nav-link-text">Transactions</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse" id="transactions">
                    <ul class="nav pl-4">
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-chart-pie-36"></i>
                                <p>Statistics</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-bullet-list-67"></i>
                                <p>All</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-bag-16"></i>
                                <p>Sales</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-coins"></i>
                                <p>Expenses</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-credit-card"></i>
                                <p>Income</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-send"></i>
                                <p>Transfers</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-money-coins"></i>
                                <p>Payments</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>

            <li>
                <a data-toggle="collapse" href="#inventory">
                    <i class="tim-icons icon-app"></i>
                    <span class="nav-link-text">Inventory</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse" id="inventory">
                    <ul class="nav pl-4">
                        <li>
                            <a href="">
                                <i class="tim-icons icon-chart-pie-36"></i>
                                <p>Statistics</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-notes"></i>
                                <p>Products</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-tag"></i>
                                <p>Categoríes</p>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="tim-icons icon-paper"></i>
                                <p>Receipts</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li> --}}

            <li class="{{ request()->is('admin/contact') ? 'active' : '' }}">
                <a href="{{ route('contact.index') }}">
                    <i class="tim-icons icon-mobile"></i>
                    <p>Contact</p>
                </a>
            </li>

        </ul>
    </div>
</div>